// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvLCR8sa7QvthG2wPVqcyug4dksTKJeBQ',
    appId: '1:563681575611:web:efebdf31d5d81166745f9e',
    messagingSenderId: '563681575611',
    projectId: 'smartbite-flutter-app',
    authDomain: 'smartbite-flutter-app.firebaseapp.com',
    storageBucket: 'smartbite-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADz2OJB61HWLaWnZSRc5oqCCy4ugHKtfI',
    appId: '1:563681575611:android:23efc0f6b0ca161e745f9e',
    messagingSenderId: '563681575611',
    projectId: 'smartbite-flutter-app',
    storageBucket: 'smartbite-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-AAal3SHv7u-YV_5Fs2RKQJ2IZ-tXffs',
    appId: '1:563681575611:ios:c68c589264019cc3745f9e',
    messagingSenderId: '563681575611',
    projectId: 'smartbite-flutter-app',
    storageBucket: 'smartbite-flutter-app.firebasestorage.app',
    iosBundleId: 'com.smartbite.smartbite',
  );
}
